- hosts: workstation
  gather_facts: false
  tasks:
  - name: OpenStack servers
    os_server_facts:
     cloud: ospcloud
     server: 'frontend'
    register: openstack_info
    tags:
      - osp.smoke
### Retrieve osp groups  ###########
  - name: Fetch Instance Info
    os_server_facts:
     cloud: ospcloud
     region_name: RegionOne
    register: result
  - debug: var=result.ansible_facts.openstack_servers
  - name: Add host
    add_host:
     name: "{{ item.public_v4 }}"
     group: "{{ item.metadata.group }}"
     ansible_ssh_private_key_file: ~/.ssh/openstack.pem
     ansible_ssh_user: cloud-user
    with_items: "{{result.ansible_facts.openstack_servers}}"
  - name: Add host
    add_host:
     name: "{{ item.public_v4 }}"
     group: "{{ item.metadata.deployment_name }}"
     ansible_ssh_private_key_file: ~/.ssh/openstack.pem
     ansible_ssh_user: cloud-user
    with_items: "{{result.ansible_facts.openstack_servers}}"
####
  - name: Curl website
    uri: 
      url: "http://{{ groups.frontends.0 }}"
      return_content: true
    register: webpage
    tags:
      - osp.smoke

  - name: Fail if 'Ansible has done its job' is not in the page content
    fail:
    when: "'Ansible has done its job' not in webpage.content"
    tags:
      - osp.smoke
