- hosts: frontends
  gather_facts: false
  tasks:
  - name: Use Uri module for writing smoke test.
    uri:
      url: "http://{{ groups.frontends.0 }}"
      return_content: true
    register: webpage
    tags:
      - aws.smoke
