---
- name: copy repo file to target hosts
  template:
    src: ./templates/{{ REPO_FILE }}
    dest: /etc/yum.repos.d/{{ REPO_FILE }}
    mode: 0644
  vars:
    REPO_FILE: "open_three-tier-app.repo"
  tags:
    - enable_target_host_repos

- name: set meaningful hostnames from inventory
  hostname:
    name: "{{ inventory_hostname }}"
  tags:
    - set_target_hostnames
